# Generated by Django 4.1.7 on 2023-04-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_task_author_task_executor_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(null=True, to="main.tag"),
        ),
    ]
