# Generated by Django 4.1.7 on 2023-04-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_of_creation",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(to="main.tag"),
        ),
    ]
