# Generated by Django 4.1.7 on 2023-04-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_task_date_of_creation_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_of_change",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_of_creation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
